INSERT INTO ORGANIZATION (ID, NAME, ADDRESS, INFORMATION) VALUES (1, 'name1', 'address1', 'info1');
INSERT INTO ORGANIZATION (ID, NAME, ADDRESS, INFORMATION) VALUES (2, 'name2', 'address2', 'info2');
INSERT INTO ORGANIZATION (ID, NAME, ADDRESS, INFORMATION) VALUES (3, 'name3', 'address3', 'info3');